### ISSUE TITLE
[Suggestion] The namespace of the custom biomes can be modified.

### ISSUE THREAD

**Issue by PanBimboBoy** [CJCrafter/BiomeManager#4]
### Description

To be able to set the biome namespace when creating it, for example a command would be:
`/bm create genkiru:spawn`
The namespace `genkiru` and the biome name `spawn`.
&
can be set after it has been created with the command 
`/biomemanager rename biomemanager:spawn genkiru:spawn`

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
The rename command is unfortunately impossible. You have to first delete the biome then make a new one

**Comment by CJCrafter** [comment]
The namespace has been possible for some time now
